name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set REPOSITORY_NAME environment
        run: echo REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F / '{print $2}') >> $GITHUB_ENV
        shell: bash

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.REPOSITORY_NAME }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/buildcache:base
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/buildcache:base,mode=max
